---
title: "2024 B-corp graphs"
format: html
editor: visual
execute: 
  echo: false
---

```{r}
#| include: false
options(scipen = 999)

library(ggplot2)
library(tidyverse)
library(here)

pydf <- read.csv(here("data", "pypi_stats.csv"), col.names = c("date", "downloads", "pkg"))
rdf <- read.csv(here("data","rpkgs.csv"), col.names = c("date", "downloads", "pkg"))
tidyvdf <- read.csv(here("data","tidyverse_pkgs.csv"), col.names = c("date", "downloads", "pkg"))
tidymdf <- read.csv(here("data", "tidymodels_pkgs.csv"), col.names = c("date", "downloads", "pkg"))
rlibdf <- read.csv(here("data","rlib_pkgs.csv"), col.names = c("date", "downloads", "pkg"))
rcondf <- read.csv(here("data","rcon_pkgs.csv"), col.names = c("date", "downloads", "pkg"))

rstudiodf <- read.csv(here("data","rstudio_os_dls.csv"), col.names = c("date", "downloads"))
rstudiodf$pkg <- "RStudio"

quarto_rstudio_dls <- read.csv(here("data", "quarto_rstudio_dls.csv"), col.names = c("date", "downloads"))
quarto_rstudio_dls$pkg <- "quarto"

quarto_gh_dls <- read.csv(here("data", "quarto_gh_downloads.csv"), col.names = c("date", "name", "downloads"))
quarto_gh_dls$date <- as.character(as.Date(quarto_gh_dls$date))

singlepltfunc <- function(df, package) { 
  return(
    df %>% 
    filter(pkg == package) %>%
    ggplot(aes(x=as.Date(date), y=cumsum(as.numeric(downloads)))) + 
    geom_line() +  
    scale_x_date(labels=scales::label_date_short()) + 
    scale_y_continuous(labels = scales::comma) +
    xlab("Date") + 
    ylab("Cumulative Downloads") + 
    ggtitle(package) + 
    theme_minimal() 
  )
}
```

## Quarto

```{r}
quarto_rstudio_by_version <- quarto_rstudio_dls %>% 
  summarise(downloads = sum(downloads)) %>%
  mutate(minor_version = "0.9")

quarto_by_version <- quarto_gh_dls %>% 
  filter(!str_detect(name, "changelog"), !str_detect(name, "checksums")) %>%
  mutate(
    version = str_extract(name, "[01]\\.[0-9]\\.[0-9]+"),
    minor_version = str_extract(version, "[01]\\.[0-9]")
  ) %>% 
  bind_rows(quarto_rstudio_by_version) %>%
  group_by(minor_version) %>%
  summarise(
    total = sum(downloads),
    min_date = min(as.Date(date)),
    max_date = max(as.Date(date))
  ) %>%
  mutate(minor_version = if_else(minor_version == 1.5, "1.5\nPre-release", minor_version))

quarto_by_version %>%
  ggplot(aes(minor_version, cumsum(total))) +
    geom_line(aes(group = 1)) + 
    scale_y_continuous(labels = scales::comma) +
    xlab("Minor Version") +
    ylab("Cumulative Downloads") +
    ggtitle("Quarto") + 
    theme_minimal()
    
```

## Shiny

```{r}
#TODO: should we stack these into a single graph?
singlepltfunc(pydf, "shiny")
singlepltfunc(rdf, "shiny")
```

## gt / great tables

```{r}
#TODO: stack these into a single graph? clean up x axis date range
singlepltfunc(pydf, "great_tables")
singlepltfunc(rdf, "gt")
```

## Vetiver

```{r}
#TODO: stack these into a single graph? clean up x axis date range
singlepltfunc(pydf, "vetiver")
singlepltfunc(rdf, "vetiver")
```

## Plotnine

```{r}
singlepltfunc(pydf, "plotnine")
```

## Siuba

```{r}
singlepltfunc(pydf, "siuba")
```

## Rstudio

```{r}
singlepltfunc(rstudiodf, "RStudio")
```

## Tidyverse

```{r}
tidyvdf %>% 
  group_by(date) %>% 
  summarise(downloads = sum(downloads)) -> tidyvdf
tidyvdf$pkg <- "Tidyverse"
  
singlepltfunc(tidyvdf, "Tidyverse")
```

## Tidymodels

```{r}
tidymdf %>% 
  group_by(date) %>% 
  summarise(downloads = sum(downloads)) -> tidymdf
tidymdf$pkg <- "Tidymodels"
  
singlepltfunc(tidymdf, "Tidymodels")
```

## Connectivity

```{r}
rcondf %>% 
  group_by(date) %>% 
  summarise(downloads = sum(downloads)) -> rcondf
rcondf$pkg <- "R Connectivity"
  
singlepltfunc(rcondf, "R Connectivity")
```

## R-lib

```{r}
rlibdf %>% 
  group_by(date) %>% 
  summarise(downloads = sum(downloads)) -> rlibdf
rlibdf$pkg <- "R-Lib"
  
singlepltfunc(rlibdf, "R-Lib")
```
